- title: Ballerina OpenAPI support
  url: #
  sublinks:
    - title: Generate a Ballerina service 
      url: /learn/ballerina-openapi-support/#generate-a-ballerina-service
      sublinks:
        - title: Generate from tags
          url: /learn/ballerina-openapi-support/#generate-from-tags
          active: generate-from-tags
    - title: Export an OpenAPI contract 
      url: /learn/ballerina-openapi-support/#export-an-openapi-contract
      sublinks:
        - title: Export in JSON format
          url: /learn/ballerina-openapi-support/#export-in-json-format
          active: export-in-json-format
        - title: Export for a given service
          url: /learn/ballerina-openapi-support/#export-for-a-given-service
          active: export-for-a-given-service
        - title: Export with a given title and version
          url: /learn/ballerina-openapi-support/#export-with-a-given-title-and-version
          active: export-with-a-given-title-and-version
    - title: OpenAPI validator compiler plugin
      url: /learn/ballerina-openapi-support/#openapi-validator-compiler-plugin
      active: openapi-validator-compiler-plugin
    - title: Generate a Ballerina client 
      url: /learn/ballerina-openapi-support/#generate-a-ballerina-client
      sublinks:
        - title: Generate with boiler-plate tests
          url: /learn/ballerina-openapi-support/#generate-with-boiler-plate-tests
          active: generate-with-boiler-plate-tests
        - title: Generate with nillable types
          url: /learn/ballerina-openapi-support/#generate-with-nillable-types
          active: generate-with-nillable-types
    - title: Publish your client
      url: /learn/ballerina-openapi-support/#publish-your-client
      active: publish-your-client
    - title: Command reference
      url: /learn/ballerina-openapi-support/#command-reference
      active: command-reference
    - title: Annotation reference
      url: /learn/ballerina-openapi-support/#annotation-reference
      active: annotation-reference
